// lib/categories.js
// Общий список категорий для скролла и формы создания

export const CATEGORY_DEFS = [
  {
    key: "kids",
    icon: "🧸",
    ua: "Дитячий світ",
    ru: "Детский мир",
    en: "Kids & babies",
    labelKey: "cat_kids",
  },
  {
    key: "realty",
    icon: "🏠",
    ua: "Нерухомість",
    ru: "Недвижимость",
    en: "Real estate",
    labelKey: "cat_realty",
  },
  {
    key: "auto",
    icon: "🚗",
    ua: "Авто",
    ru: "Автомобили",
    en: "Cars",
    labelKey: "cat_auto",
  },
  {
    key: "autoparts",
    icon: "🛠️",
    ua: "Запчастини",
    ru: "Запчасти",
    en: "Auto parts",
    labelKey: "cat_autoparts",
  },
  {
    key: "jobs",
    icon: "💼",
    ua: "Робота",
    ru: "Работа",
    en: "Jobs",
    labelKey: "cat_jobs",
  },
  {
    key: "pets",
    icon: "🐾",
    ua: "Тварини",
    ru: "Животные",
    en: "Pets",
    labelKey: "cat_pets",
  },

  // НОВАЯ КАТЕГОРИЯ — МЕБЕЛЬ
  {
    key: "furniture",
    icon: "🛋",
    ua: "Меблі",
    ru: "Мебель",
    en: "Furniture",
    labelKey: "cat_furniture",
  },

  {
    key: "home_garden",
    icon: "🪴",
    ua: "Дім і сад",
    ru: "Дом и сад",
    en: "Home & garden",
    labelKey: "cat_home_garden",
  },
  {
    key: "electronics",
    icon: "📱",
    ua: "Електроніка",
    ru: "Электроника",
    en: "Electronics",
    labelKey: "cat_electronics",
  },
  {
    key: "business",
    icon: "📊",
    ua: "Бізнес та послуги",
    ru: "Бизнес и услуги",
    en: "Business & services",
    labelKey: "cat_business",
  },
  {
    key: "fashion",
    icon: "👗",
    ua: "Мода і стиль",
    ru: "Мода и стиль",
    en: "Fashion & style",
    labelKey: "cat_fashion",
  },
  {
    key: "hobby_sport",
    icon: "🎯",
    ua: "Хобі, відпочинок і спорт",
    ru: "Хобби, отдых и спорт",
    en: "Hobby, leisure & sport",
    labelKey: "cat_hobby_sport",
  },
  {
    key: "free",
    icon: "🎁",
    ua: "Віддам безкоштовно",
    ru: "Отдам бесплатно",
    en: "Give away free",
    labelKey: "cat_free",
  },
  {
    key: "exchange",
    icon: "🔁",
    ua: "Обмін",
    ru: "Обмен",
    en: "Exchange",
    labelKey: "cat_exchange",
  },
];
