// lib/categories.js
// Общий список категорий для скролла и формы создания

export const CATEGORY_DEFS = [
  {
    key: "kids",
    icon: "🧸",
    ua: "Дитячий світ",
    ru: "Детский мир",
    en: "Kids & babies",
    en: "Kids & babies",
    labelKey: "cat_kids",
    color: "text-pink-600",
    bg: "bg-pink-50",
    filters: [
      {
        key: "subtype",
        label: { ru: "Тип товара", ua: "Тип товару", en: "Type" },
        type: "select",
        options: [
          { value: "clothing", label: { ru: "Одежда", ua: "Одяг", en: "Clothing" } },
          { value: "shoes", label: { ru: "Обувь", ua: "Взуття", en: "Shoes" } },
          { value: "toys", label: { ru: "Игрушки", ua: "Іграшки", en: "Toys" } },
          { value: "strollers", label: { ru: "Коляски", ua: "Візочки", en: "Strollers" } },
          { value: "furniture", label: { ru: "Мебель", ua: "Меблі", en: "Furniture" } },
          { value: "transport", label: { ru: "Транспорт", ua: "Транспорт", en: "Transport" } },
          { value: "food", label: { ru: "Питание", ua: "Харчування", en: "Food" } },
          { value: "books", label: { ru: "Книги", ua: "Книги", en: "Books" } },
        ],
      },
      {
        key: "age",
        label: { ru: "Возраст", ua: "Вік", en: "Age" },
        type: "select",
        options: [
          { value: "0-6m", label: { ru: "0–6 мес", ua: "0–6 міс", en: "0–6 m" } },
          { value: "6-12m", label: { ru: "6–12 мес", ua: "6–12 міс", en: "6–12 m" } },
          { value: "1-2y", label: { ru: "1–2 года", ua: "1–2 роки", en: "1–2 y" } },
          { value: "2-4y", label: { ru: "2–4 года", ua: "2–4 роки", en: "2–4 y" } },
          { value: "4-6y", label: { ru: "4–6 лет", ua: "4–6 років", en: "4–6 y" } },
          { value: "6plus", label: { ru: "6+ лет", ua: "6+ років", en: "6+ y" } },
        ],
      },
      {
        key: "gender",
        label: { ru: "Пол", ua: "Стать", en: "Gender" },
        type: "select",
        options: [
          { value: "boy", label: { ru: "Мальчик", ua: "Хлопчик", en: "Boy" } },
          { value: "girl", label: { ru: "Девочка", ua: "Дівчинка", en: "Girl" } },
          { value: "unisex", label: { ru: "Унисекс", ua: "Унісекс", en: "Unisex" } },
        ],
      },
      {
        key: "condition",
        label: { ru: "Состояние", ua: "Стан", en: "Condition" },
        type: "select",
        options: [
          { value: "new", label: { ru: "Новое", ua: "Нове", en: "New" } },
          { value: "like_new", label: { ru: "Как новое", ua: "Як нове", en: "Like new" } },
          { value: "used", label: { ru: "Б/у", ua: "Б/в", en: "Used" } },
        ],
      },
      {
        key: "brand",
        label: { ru: "Бренд", ua: "Бренд", en: "Brand" },
        type: "text",
      },
      {
        key: "material",
        label: { ru: "Материал", ua: "Матеріал", en: "Material" },
        type: "text",
      },
      {
        key: "size_clothes",
        label: { ru: "Размер одежды (рост)", ua: "Розмір одягу (зріст)", en: "Clothing size (height)" },
        type: "select",
        options: [
             { value: "50", label: { ru: "50", ua: "50", en: "50" } },
             { value: "56", label: { ru: "56", ua: "56", en: "56" } },
             { value: "62", label: { ru: "62", ua: "62", en: "62" } },
             { value: "68", label: { ru: "68", ua: "68", en: "68" } },
             { value: "74", label: { ru: "74", ua: "74", en: "74" } },
             { value: "80", label: { ru: "80 (9-12 мес)", ua: "80 (9-12 міс)", en: "80" } },
             { value: "86", label: { ru: "86 (12-18 мес)", ua: "86 (12-18 міс)", en: "86" } },
             { value: "92", label: { ru: "92 (18-24 мес)", ua: "92 (18-24 міс)", en: "92" } },
             { value: "98", label: { ru: "98 (2-3 года)", ua: "98 (2-3 роки)", en: "98" } },
             { value: "104", label: { ru: "104 (3-4 года)", ua: "104 (3-4 роки)", en: "104" } },
             { value: "110", label: { ru: "110 (4-5 лет)", ua: "110 (4-5 років)", en: "110" } },
             { value: "116", label: { ru: "116 (5-6 лет)", ua: "116 (5-6 років)", en: "116" } },
             { value: "122", label: { ru: "122 (6-7 лет)", ua: "122 (6-7 років)", en: "122" } },
             { value: "128", label: { ru: "128 (7-8 лет)", ua: "128 (7-8 років)", en: "128" } },
             { value: "134", label: { ru: "134 (8-9 лет)", ua: "134 (8-9 років)", en: "134" } },
             { value: "140", label: { ru: "140 (9-10 лет)", ua: "140 (9-10 років)", en: "140" } },
             { value: "146", label: { ru: "146", ua: "146", en: "146" } },
             { value: "152", label: { ru: "152", ua: "152", en: "152" } },
             { value: "158", label: { ru: "158", ua: "158", en: "158" } },
             { value: "164", label: { ru: "164", ua: "164", en: "164" } },
        ]
      },
      {
        key: "size_shoes",
        label: { ru: "Размер обуви", ua: "Розмір взуття", en: "Shoe size" },
        type: "select",
        options: [
             { value: "16", label: { ru: "16", ua: "16", en: "16" } },
             { value: "17", label: { ru: "17", ua: "17", en: "17" } },
             { value: "18", label: { ru: "18", ua: "18", en: "18" } },
             { value: "19", label: { ru: "19", ua: "19", en: "19" } },
             { value: "20", label: { ru: "20", ua: "20", en: "20" } },
             { value: "21", label: { ru: "21", ua: "21", en: "21" } },
             { value: "22", label: { ru: "22", ua: "22", en: "22" } },
             { value: "23", label: { ru: "23", ua: "23", en: "23" } },
             { value: "24", label: { ru: "24", ua: "24", en: "24" } },
             { value: "25", label: { ru: "25", ua: "25", en: "25" } },
             { value: "26", label: { ru: "26", ua: "26", en: "26" } },
             { value: "27", label: { ru: "27", ua: "27", en: "27" } },
             { value: "28", label: { ru: "28", ua: "28", en: "28" } },
             { value: "29", label: { ru: "29", ua: "29", en: "29" } },
             { value: "30", label: { ru: "30", ua: "30", en: "30" } },
             { value: "31", label: { ru: "31", ua: "31", en: "31" } },
             { value: "32", label: { ru: "32", ua: "32", en: "32" } },
             { value: "33", label: { ru: "33", ua: "33", en: "33" } },
             { value: "34", label: { ru: "34", ua: "34", en: "34" } },
             { value: "35", label: { ru: "35", ua: "35", en: "35" } },
             { value: "36", label: { ru: "36", ua: "36", en: "36" } },
             { value: "37", label: { ru: "37", ua: "37", en: "37" } },
             { value: "38", label: { ru: "38", ua: "38", en: "38" } },
             { value: "39", label: { ru: "39", ua: "39", en: "39" } },
        ]
      },
    ],
  },
  {
    key: "realty",
    icon: "🏠",
    ua: "Нерухомість",
    ru: "Недвижимость",
    en: "Real estate",
    en: "Real estate",
    labelKey: "cat_realty",
    color: "text-emerald-600",
    bg: "bg-emerald-50",
    filters: [
      {
        key: "subtype",
        label: { ru: "Тип", ua: "Тип", en: "Type" },
        type: "select",
        options: [
          { value: "apartment", label: { ru: "Квартира", ua: "Квартира", en: "Apartment" } },
          { value: "house", label: { ru: "Дом", ua: "Будинок", en: "House" } },
          { value: "room", label: { ru: "Комната", ua: "Кімната", en: "Room" } },
          { value: "commercial", label: { ru: "Коммерческая", ua: "Комерційна", en: "Commercial" } },
          { value: "garage", label: { ru: "Гараж", ua: "Гараж", en: "Garage" } },
        ],
      },
      {
        key: "deal_type",
        label: { ru: "Сделка", ua: "Угода", en: "Deal type" },
        type: "select",
        options: [
            { value: "sale", label: { ru: "Продажа", ua: "Продаж", en: "Sale" } },
            { value: "rent", label: { ru: "Аренда", ua: "Оренда", en: "Rent" } },
            { value: "daily", label: { ru: "Посуточно", ua: "Подобово", en: "Daily rent" } },
        ]
      },
      {
        key: "area",
        label: { ru: "Площадь (м²)", ua: "Площа (м²)", en: "Area (m²)" },
        type: "range",
      },
      {
        key: "rooms",
        label: { ru: "Количество комнат", ua: "Кількість кімнат", en: "Rooms" },
        type: "select",
        options: [
            { value: "1", label: { ru: "1", ua: "1", en: "1" } },
            { value: "2", label: { ru: "2", ua: "2", en: "2" } },
            { value: "3", label: { ru: "3", ua: "3", en: "3" } },
            { value: "4plus", label: { ru: "4+", ua: "4+", en: "4+" } },
        ]
      },
      {
        key: "floor",
        label: { ru: "Этаж", ua: "Поверх", en: "Floor" },
        type: "number",
      },
      {
        key: "total_floors",
        label: { ru: "Этажность дома", ua: "Поверховість будинку", en: "Total floors" },
        type: "number",
      },
      {
        key: "building_type",
        label: { ru: "Тип здания", ua: "Тип будинку", en: "Building type" },
        type: "select",
        options: [
            { value: "panel", label: { ru: "Панель", ua: "Панель", en: "Panel" } },
            { value: "brick", label: { ru: "Кирпич", ua: "Цегла", en: "Brick" } },
            { value: "block", label: { ru: "Блок", ua: "Блок", en: "Block" } },
        ]
      },
      {
        key: "heating",
        label: { ru: "Отопление", ua: "Опалення", en: "Heating" },
        type: "select",
        options: [
          { value: "central", label: { ru: "Центральное", ua: "Центральне", en: "Central" } },
          { value: "individual", label: { ru: "Индивидуальное", ua: "Індивідуальне", en: "Individual" } },
          { value: "gas", label: { ru: "Газ", ua: "Газ", en: "Gas" } },
          { value: "electric", label: { ru: "Электро", ua: "Електро", en: "Electric" } },
        ],
      },
      {
        key: "furnished",
        label: { ru: "Меблировка", ua: "Меблі", en: "Furnished" },
        type: "boolean",
      },
      {
        key: "bathroom",
        label: { ru: "Санузел", ua: "Санвузол", en: "Bathroom" },
        type: "select",
        options: [
            { value: "combined", label: { ru: "Совмещенный", ua: "Суміщений", en: "Combined" } },
            { value: "separated", label: { ru: "Раздельный", ua: "Роздільний", en: "Separated" } },
        ]
      },
      {
        key: "balcony",
        label: { ru: "Балкон", ua: "Балкон", en: "Balcony" },
        type: "boolean",
      },
      {
        key: "pets_allowed",
        label: { ru: "Животные разрешены", ua: "Тварини дозволені", en: "Pets allowed" },
        type: "boolean",
      },
      {
        key: "utilities_included",
        label: { ru: "Коммунальные включены", ua: "Комунальні включені", en: "Utilities included" },
        type: "boolean",
      },
      {
        key: "deposit",
        label: { ru: "Залог", ua: "Застава", en: "Deposit" },
        type: "boolean",
      },
    ],
  },
  {
    key: "auto",
    icon: "🚗",
    ua: "Авто",
    ru: "Автомобили",
    en: "Cars",
    en: "Cars",
    labelKey: "cat_auto",
    color: "text-blue-600",
    bg: "bg-blue-50",
    filters: [
      {
        key: "brand",
        label: { ru: "Марка", ua: "Марка", en: "Brand" },
        type: "text",
      },
      {
        key: "model",
        label: { ru: "Модель", ua: "Модель", en: "Model" },
        type: "text",
      },
      {
        key: "year",
        label: { ru: "Год выпуска", ua: "Рік випуску", en: "Year" },
        type: "range",
      },
      {
        key: "mileage",
        label: { ru: "Пробег (км)", ua: "Пробіг (км)", en: "Mileage (km)" },
        type: "range",
      },
      {
        key: "fuel_type",
        label: { ru: "Тип топлива", ua: "Тип пального", en: "Fuel type" },
        type: "select",
        options: [
          { value: "gas", label: { ru: "Газ", ua: "Газ", en: "Gas" } },
          { value: "petrol", label: { ru: "Бензин", ua: "Бензин", en: "Petrol" } },
          { value: "diesel", label: { ru: "Дизель", ua: "Дизель", en: "Diesel" } },
          { value: "hybrid", label: { ru: "Гибрид", ua: "Гібрид", en: "Hybrid" } },
          { value: "electric", label: { ru: "Электро", ua: "Електро", en: "Electric" } },
        ],
      },
      {
        key: "transmission",
        label: { ru: "КПП", ua: "КПП", en: "Transmission" },
        type: "select",
        options: [
          { value: "automatic", label: { ru: "Автомат", ua: "Автомат", en: "Automatic" } },
          { value: "manual", label: { ru: "Механика", ua: "Механіка", en: "Manual" } },
          { value: "robot", label: { ru: "Робот", ua: "Робот", en: "Robot" } },
        ],
      },
      {
        key: "drive_type",
        label: { ru: "Привод", ua: "Привід", en: "Drive type" },
        type: "select",
        options: [
          { value: "fwd", label: { ru: "Передний", ua: "Передній", en: "FWD" } },
          { value: "rwd", label: { ru: "Задний", ua: "Задній", en: "RWD" } },
          { value: "awd", label: { ru: "Полный", ua: "Повний", en: "AWD" } },
        ],
      },
      {
        key: "body_type",
        label: { ru: "Тип кузова", ua: "Тип кузова", en: "Body type" },
        type: "select",
        options: [
            { value: "sedan", label: { ru: "Седан", ua: "Седан", en: "Sedan" } },
            { value: "suv", label: { ru: "Внедорожник", ua: "Позашляховик", en: "SUV" } },
            { value: "hatchback", label: { ru: "Хэтчбек", ua: "Хетчбек", en: "Hatchback" } },
            { value: "wagon", label: { ru: "Универсал", ua: "Універсал", en: "Wagon" } },
            { value: "coupe", label: { ru: "Купе", ua: "Купе", en: "Coupe" } },
            { value: "minivan", label: { ru: "Минивэн", ua: "Мінівен", en: "Minivan" } },
        ]
      },
      {
        key: "color",
        label: { ru: "Цвет", ua: "Колір", en: "Color" },
        type: "text",
      },
      {
        key: "customs_cleared",
        label: { ru: "Растаможен", ua: "Розмитнений", en: "Customs cleared" },
        type: "boolean",
      },
      {
        key: "broken",
        label: { ru: "Битый", ua: "Битий", en: "Broken" },
        type: "boolean",
      },
      {
        key: "service_history",
        label: { ru: "Сервисная история", ua: "Сервісна історія", en: "Service history" },
        type: "boolean",
      },
    ],
  },
  {
    key: "autoparts",
    icon: "🛠️",
    ua: "Запчастини",
    ru: "Запчасти",
    en: "Auto parts",
    en: "Auto parts",
    labelKey: "cat_autoparts",
    color: "text-slate-600",
    bg: "bg-slate-50",
    filters: [
      {
        key: "subtype",
        label: { ru: "Тип детали", ua: "Тип деталі", en: "Part type" },
        type: "select",
        options: [
          { value: "engine", label: { ru: "Двигатель", ua: "Двигун", en: "Engine" } },
          { value: "chassis", label: { ru: "Ходовая", ua: "Ходова", en: "Chassis" } },
          { value: "body", label: { ru: "Кузов", ua: "Кузов", en: "Body" } },
          { value: "electric", label: { ru: "Электрика", ua: "Електрика", en: "Electric" } },
          { value: "tuning", label: { ru: "Тюнинг", ua: "Тюнінг", en: "Tuning" } },
        ],
      },
      {
        key: "brand",
        label: { ru: "Марка авто", ua: "Марка авто", en: "Car brand" },
        type: "text",
      },
      {
        key: "model",
        label: { ru: "Модель авто", ua: "Модель авто", en: "Car model" },
        type: "text",
      },
      {
        key: "condition",
        label: { ru: "Состояние", ua: "Стан", en: "Condition" },
        type: "select",
        options: [
          { value: "new", label: { ru: "Новое", ua: "Нове", en: "New" } },
          { value: "used", label: { ru: "Б/у", ua: "Б/в", en: "Used" } },
        ],
      },
      {
        key: "origin",
        label: { ru: "Оригинальность", ua: "Оригінальність", en: "Originality" },
        type: "select",
        options: [
          { value: "original", label: { ru: "Оригинал", ua: "Оригінал", en: "Original" } },
          { value: "analog", label: { ru: "Аналог", ua: "Аналог", en: "Analog" } },
        ],
      },
    ],
  },
  {
    key: "jobs",
    icon: "💼",
    ua: "Робота",
    ru: "Работа",
    en: "Jobs",
    en: "Jobs",
    labelKey: "cat_jobs",
    color: "text-amber-600",
    bg: "bg-amber-50",
    filters: [
      {
        key: "employment_type",
        label: { ru: "Тип занятости", ua: "Тип зайнятості", en: "Employment type" },
        type: "select",
        options: [
          { value: "full", label: { ru: "Полная", ua: "Повна", en: "Full-time" } },
          { value: "part", label: { ru: "Частичная", ua: "Часткова", en: "Part-time" } },
          { value: "gig", label: { ru: "Подработка", ua: "Підробіток", en: "Gig" } },
        ],
      },
      {
        key: "format",
        label: { ru: "Формат", ua: "Формат", en: "Format" },
        type: "select",
        options: [
          { value: "office", label: { ru: "Офис", ua: "Офіс", en: "Office" } },
          { value: "remote", label: { ru: "Удаленка", ua: "Віддалено", en: "Remote" } },
          { value: "hybrid", label: { ru: "Гибрид", ua: "Гібрид", en: "Hybrid" } },
        ],
      },
      {
        key: "experience",
        label: { ru: "Опыт", ua: "Досвід", en: "Experience" },
        type: "select",
        options: [
          { value: "none", label: { ru: "Без опыта", ua: "Без досвіду", en: "No experience" } },
          { value: "1plus", label: { ru: "1+", ua: "1+", en: "1+" } },
          { value: "3plus", label: { ru: "3+", ua: "3+", en: "3+" } },
          { value: "5plus", label: { ru: "5+", ua: "5+", en: "5+" } },
        ],
      },
      {
        key: "salary",
        label: { ru: "Зарплата", ua: "Зарплата", en: "Salary" },
        type: "range",
      },
      {
        key: "industry",
        label: { ru: "Сфера", ua: "Сфера", en: "Industry" },
        type: "select",
        options: [
            { value: "retail", label: { ru: "Розничная торговля", ua: "Роздрібна торгівля", en: "Retail" } },
            { value: "transport", label: { ru: "Транспорт / Логистика", ua: "Транспорт / Логістика", en: "Transport / Logistics" } },
            { value: "construction", label: { ru: "Строительство", ua: "Будівництво", en: "Construction" } },
            { value: "bar_restaurant", label: { ru: "Бар / Рестораны", ua: "Бар / Ресторани", en: "Bar / Restaurants" } },
            { value: "mnfg", label: { ru: "Производство", ua: "Виробництво", en: "Manufacturing" } },
            { value: "admin", label: { ru: "Администрация", ua: "Адміністрація", en: "Administration" } },
            { value: "cleaning", label: { ru: "Клининг", ua: "Клінінг", en: "Cleaning" } },
            { value: "domestic", label: { ru: "Домашний персонал", ua: "Домашній персонал", en: "Domestic staff" } },
            { value: "education", label: { ru: "Образование", ua: "Освіта", en: "Education" } },
            { value: "it", label: { ru: "IT / Телеком", ua: "IT / Телеком", en: "IT / Telecom" } },
            { value: "finance", label: { ru: "Финансы / Бухгалтерия", ua: "Фінанси / Бухгалтерія", en: "Finance / Accounting" } },
            { value: "security", label: { ru: "Охрана / Безопасность", ua: "Охорона / Безпека", en: "Security" } },
            { value: "medicine", label: { ru: "Медицина / Фармация", ua: "Медицина / Фармація", en: "Medicine / Pharmacy" } },
            { value: "agriculture", label: { ru: "Сельское хозяйство", ua: "Сільське господарство", en: "Agriculture" } },
            { value: "service", label: { ru: "Сфера услуг", ua: "Сфера послуг", en: "Service sector" } },
            { value: "other", label: { ru: "Другие сферы", ua: "Інші сфери", en: "Other sectors" } },
        ]
      },
    ],
  },
  {
    key: "translations",
    icon: "🗣️",
    ua: "Переклади та супровід",
    ru: "Переводы и сопровождение",
    en: "Translations & Accompaniment",
    labelKey: "cat_translations",
    color: "text-cyan-600",
    bg: "bg-cyan-50",
    filters: [
      {
        key: "subtype",
        label: { ru: "Тип услуги", ua: "Тип послуги", en: "Service type" },
        type: "select",
        options: [
          { value: "docs_help", label: { ru: "Помощь с документами", ua: "Допомога з документами", en: "Help with documents" } },
          { value: "translation", label: { ru: "Переводы и сопровождение", ua: "Переклади та супровід", en: "Translations and Accompaniment" } },
          { value: "accompaniment", label: { ru: "Сопровождение на термине", ua: "Супровід на терміні", en: "Accompaniment at appointment" } },
        ],
      },
      {
        key: "language",
        label: { ru: "Язык", ua: "Мова", en: "Language" },
        type: "select",
        options: [
            { value: "de", label: { ru: "Немецкий", ua: "Німецька", en: "German" } },
            { value: "en", label: { ru: "Английский", ua: "Англійська", en: "English" } },
            { value: "ru", label: { ru: "Русский", ua: "Російська", en: "Russian" } },
            { value: "ua", label: { ru: "Украинский", ua: "Українська", en: "Ukrainian" } },
            { value: "other", label: { ru: "Другой", ua: "Інша", en: "Other" } },
        ]
      },
      {
        key: "payment_type",
        label: { ru: "Оплата", ua: "Оплата", en: "Payment" },
        type: "select",
        options: [
            { value: "fixed", label: { ru: "Фиксированная", ua: "Фіксована", en: "Fixed price" } },
            { value: "hourly", label: { ru: "Почасовая", ua: "Погодинна", en: "Hourly rate" } },
        ]
      },

    ],
  },
  {
    key: "pets",
    icon: "🐾",
    ua: "Тварини",
    ru: "Животные",
    en: "Pets",
    en: "Pets",
    labelKey: "cat_pets",
    color: "text-orange-600",
    bg: "bg-orange-50",
    filters: [
      {
        key: "product_type",
        label: { ru: "Категория", ua: "Категорія", en: "Category" },
        type: "select",
        options: [
            { value: "pet", label: { ru: "Домашние животные", ua: "Домашні тварини", en: "Pets" } },
            { value: "farm", label: { ru: "Фермерские животные", ua: "Фермерські тварини", en: "Farm animals" } },
            { value: "goods", label: { ru: "Товары для животных", ua: "Товари для тварин", en: "Pet goods" } },
        ]
      },
      // Removed subtype, breed, size, condition as requested
      {
        key: "age",
        label: { ru: "Возраст", ua: "Вік", en: "Age" },
        type: "text",
      },
      {
        key: "gender",
        label: { ru: "Пол", ua: "Стать", en: "Gender" },
        type: "select",
        options: [
          { value: "male", label: { ru: "Мальчик", ua: "Хлопчик", en: "Male" } },
          { value: "female", label: { ru: "Девочка", ua: "Дівчинка", en: "Female" } },
        ],
      },
      {
        key: "vaccinations",
        label: { ru: "Прививки", ua: "Щеплення", en: "Vaccinations" },
        type: "boolean",
      },
      {
        key: "documents",
        label: { ru: "Документы", ua: "Документи", en: "Documents" },
        type: "boolean",
      },
      {
        key: "sterilized",
        label: { ru: "Стерилизован", ua: "Стерилізований", en: "Sterilized" },
        type: "boolean",
      },
      {
        key: "goods_type",
        label: { ru: "Тип товара", ua: "Тип товару", en: "Goods type" },
        type: "select",
        options: [
            { value: "kennel", label: { ru: "Будки", ua: "Будки", en: "Kennels" } },
            { value: "cage", label: { ru: "Клетки", ua: "Клітки", en: "Cages" } },
            { value: "food", label: { ru: "Корм", ua: "Корм", en: "Food" } },
            { value: "carrier", label: { ru: "Переноски", ua: "Переноски", en: "Carriers" } },
            { value: "other", label: { ru: "Другое", ua: "Інше", en: "Other" } },
        ]
      },
    ],
  },
  {
    key: "furniture",
    icon: "🛋",
    ua: "Меблі",
    ru: "Мебель",
    en: "Furniture",
    en: "Furniture",
    labelKey: "cat_furniture",
    color: "text-teal-600",
    bg: "bg-teal-50",
    filters: [
      {
        key: "subtype",
        label: { ru: "Тип мебели", ua: "Тип меблів", en: "Furniture type" },
        type: "select",
        options: [
          { value: "living_room", label: { ru: "Гостиная", ua: "Вітальня", en: "Living room" } },
          { value: "bedroom", label: { ru: "Спальня", ua: "Спальня", en: "Bedroom" } },
          { value: "hallway", label: { ru: "Прихожая", ua: "Передпокій", en: "Hallway" } },
          { value: "kitchen", label: { ru: "Кухня", ua: "Кухня", en: "Kitchen" } },
          { value: "bathroom", label: { ru: "Ванная", ua: "Ванна", en: "Bathroom" } },
          { value: "office", label: { ru: "Офисная мебель", ua: "Офісні меблі", en: "Office furniture" } },
          { value: "cupboards", label: { ru: "Шкафы / Стенки", ua: "Шафи / Стінки", en: "Cupboards / Walls" } },
          { value: "tables_chairs", label: { ru: "Столы / Стулья", ua: "Столи / Стільці", en: "Tables / Chairs" } },
          { value: "sofas", label: { ru: "Диваны / Кресла", ua: "Дивани / Крісла", en: "Sofas / Armchairs" } },
          { value: "beds", label: { ru: "Кровати", ua: "Ліжка", en: "Beds" } },
          { value: "shelving", label: { ru: "Стеллажи", ua: "Стелажі", en: "Shelving" } },
          { value: "other", label: { ru: "Другое", ua: "Інше", en: "Other" } },
        ],
      },
      {
        key: "condition",
        label: { ru: "Состояние", ua: "Стан", en: "Condition" },
        type: "select",
        options: [
          { value: "new", label: { ru: "Новое", ua: "Нове", en: "New" } },
          { value: "used", label: { ru: "Б/у", ua: "Б/в", en: "Used" } },
        ],
      },
      {
        key: "material",
        label: { ru: "Материал", ua: "Матеріал", en: "Material" },
        type: "text",
      },
      {
        key: "dimensions",
        label: { ru: "Размеры", ua: "Розміри", en: "Dimensions" },
        type: "text",
      },
      {
        key: "manufacturer",
        label: { ru: "Производитель", ua: "Виробник", en: "Manufacturer" },
        type: "text",
      },
    ],
  },
  {
    key: "home_garden",
    icon: "🪴",
    ua: "Дім і сад",
    ru: "Дом и сад",
    en: "Home & garden",
    en: "Home & garden",
    labelKey: "cat_home_garden",
    color: "text-green-600",
    bg: "bg-green-50",
    filters: [
      {
        key: "subtype",
        label: { ru: "Тип", ua: "Тип", en: "Type" },
        type: "select",
        options: [
          { value: "decor", label: { ru: "Декор / Интерьер", ua: "Декор / Інтер'єр", en: "Decor / Interior" } },
          { value: "textiles_carpets", label: { ru: "Текстиль / Ковры", ua: "Текстиль / Килими", en: "Textiles / Carpets" } },
          { value: "lighting", label: { ru: "Освещение", ua: "Освітлення", en: "Lighting" } },
          { value: "garden", label: { ru: "Сад / Огород", ua: "Сад / Город", en: "Garden / Vegetable garden" } },
          { value: "plants", label: { ru: "Комнатные растения", ua: "Кімнатні рослини", en: "Indoor plants" } },
          { value: "tools", label: { ru: "Инструменты", ua: "Інструменти", en: "Tools" } },
          { value: "construction", label: { ru: "Все для стройки", ua: "Все для будівництва", en: "Construction" } },
          { value: "dishes", label: { ru: "Посуда", ua: "Посуд", en: "Dishes" } },
          { value: "household_chem", label: { ru: "Хоз. инвентарь / Химия", ua: "Госп. інвентар / Хімія", en: "Inventory / Chemicals" } },

        ],
      },
      {
        key: "condition",
        label: { ru: "Состояние", ua: "Стан", en: "Condition" },
        type: "select",
        options: [
          { value: "new", label: { ru: "Новое", ua: "Нове", en: "New" } },
          { value: "used", label: { ru: "Б/у", ua: "Б/в", en: "Used" } },
        ],
      },
      {
        key: "material",
        label: { ru: "Материал", ua: "Матеріал", en: "Material" },
        type: "text",
      },
      {
        key: "size",
        label: { ru: "Размер", ua: "Розмір", en: "Size" },
        type: "text",
      },
      {
        key: "manufacturer",
        label: { ru: "Производитель", ua: "Виробник", en: "Manufacturer" },
        type: "text",
      },
    ],
  },
  {
    key: "electronics",
    icon: "📱",
    ua: "Електроніка",
    ru: "Электроника",
    en: "Electronics",
    en: "Electronics",
    labelKey: "cat_electronics",
    color: "text-indigo-600",
    bg: "bg-indigo-50",
    filters: [
      {
        key: "subtype",
        label: { ru: "Категория", ua: "Категорія", en: "Category" },
        type: "select",
        options: [
          // 1. Мобильные
          { value: "mobile_phones", label: { ru: "Мобильные / смартфоны", ua: "Мобільні / смартфони", en: "Mobile phones & smartphones" } },
          { value: "phone_accessories", label: { ru: "Аксессуары к телефонам", ua: "Аксесуари до телефонів", en: "Phone accessories" } },
          { value: "phone_spare_parts", label: { ru: "Запчасти к телефонам", ua: "Запчастини до телефонів", en: "Phone spare parts" } },

          // 2. Компьютеры и комплектующие
          { value: "laptops", label: { ru: "Ноутбуки и ультрабуки", ua: "Ноутбуки та ультрабуки", en: "Laptops & ultrabooks" } },
          { value: "desktops", label: { ru: "Настольные ПК", ua: "Настільні ПК", en: "Desktop PCs" } },
          { value: "tablets", label: { ru: "Планшеты", ua: "Планшети", en: "Tablets" } },
          { value: "monitors", label: { ru: "Мониторы", ua: "Монітори", en: "Monitors" } },
          { value: "pc_components", label: { ru: "Комплектующие (видео, CPU, плати)", ua: "Комплектуючі (відео, CPU, плати)", en: "PC components (GPU, CPU, MB)" } },
          { value: "pc_peripherals", label: { ru: "Периферия (клавы, мыши)", ua: "Периферія (клавіатури, миші)", en: "Peripherals (keyboards, mice)" } },
          { value: "networking", label: { ru: "Сетевое / Wi-Fi оборудование", ua: "Мережеве / Wi-Fi обладнання", en: "Networking & Wi-Fi" } },
          { value: "storage_devices", label: { ru: "Накопители данных", ua: "Накопичувачі даних", en: "Storage devices" } },

          // 3. ТВ / видео
          { value: "tv_sets", label: { ru: "Телевизоры и панели", ua: "Телевізори та панелі", en: "TV sets & panels" } },
          { value: "projectors_screens", label: { ru: "Проекторы / экраны", ua: "Проектори / екрани", en: "Projectors & screens" } },
          { value: "tv_video_accessories", label: { ru: "Аксессуары для ТВ / видео", ua: "Аксесуари для ТВ / відео", en: "TV & video accessories" } },
          { value: "media_players", label: { ru: "Медиаплееры / ТВ-тюнеры", ua: "Медіаплеєри / ТВ-тюнери", en: "Media players & TV tuners" } },

          // 4. Аудио
          { value: "audio_speakers", label: { ru: "Акустика, колонки", ua: "Акустика, колонки", en: "Speakers & sound systems" } },
          { value: "headphones", label: { ru: "Наушники", ua: "Навушники", en: "Headphones" } },
          { value: "mp3_players", label: { ru: "MP3 / аудиоплееры", ua: "MP3 / аудіоплеєри", en: "MP3 & audio players" } },
          { value: "audio_centers", label: { ru: "Музыкальные центры, магнитолы", ua: "Музичні центри, магнітофони", en: "Hi-Fi systems & boomboxes" } },
          { value: "voice_recorders", label: { ru: "Диктофоны", ua: "Диктофони", en: "Voice recorders" } },

          // 5. Фото / видео
          { value: "photo_cameras", label: { ru: "Фотоаппараты и объективы", ua: "Фотоапарати та об'єктиви", en: "Cameras & lenses" } },
          { value: "video_cameras", label: { ru: "Видеокамеры", ua: "Відеокамери", en: "Video cameras" } },
          { value: "photo_video_accessories", label: { ru: "Аксессуары для фото / видео", ua: "Аксесуари для фото / відео", en: "Photo & video accessories" } },
          { value: "photo_frames", label: { ru: "Фоторамки / альбомы", ua: "Фоторамки / альбоми", en: "Photo frames & albums" } },
          { value: "photo_print", label: { ru: "Печать / проявка фото", ua: "Друк / проявка фото", en: "Photo printing & lab" } },

          // 6. Игры и приставки
          { value: "game_consoles", label: { ru: "Игровые приставки", ua: "Ігрові приставки", en: "Game consoles" } },
          { value: "console_games", label: { ru: "Игры для приставок", ua: "Ігри для приставок", en: "Console games" } },
          { value: "console_accessories", label: { ru: "Аксессуары для приставок", ua: "Аксесуари для приставок", en: "Console accessories" } },
          { value: "gaming_gear", label: { ru: "Товары для геймеров", ua: "Товари для геймерів", en: "Gaming gear" } },

          // 7. Техника для дома
          { value: "climate_tech", label: { ru: "Климатическая техника", ua: "Кліматична техніка", en: "Climate appliances" } },
          { value: "big_appliances", label: { ru: "Крупная бытовая техника", ua: "Велика побутова техніка", en: "Large home appliances" } },
          { value: "kitchen_appliances", label: { ru: "Кухонная техника", ua: "Кухонна техніка", en: "Kitchen appliances" } },
          { value: "vacuum_cleaners", label: { ru: "Пылесосы", ua: "Пилососи", en: "Vacuum cleaners" } },

          // 8. Прочая электроника
          { value: "wearables", label: { ru: "Смарт-часы и браслеты", ua: "Смарт-годинники та браслети", en: "Smart watches & bands" } },
          { value: "e_readers", label: { ru: "Электронные книги", ua: "Електронні книги", en: "E-book readers" } },
          { value: "gps_dashcams", label: { ru: "GPS / видеорегистраторы", ua: "GPS / відеореєстратори", en: "GPS & dashcams" } },
          { value: "calculators", label: { ru: "Калькуляторы", ua: "Калькулятори", en: "Calculators" } },
          { value: "personal_care", label: { ru: "Техника для красоты", ua: "Техніка для краси", en: "Personal care" } },
          { value: "other_electronics", label: { ru: "Другая электроника", ua: "Інша електроніка", en: "Other electronics" } },
        ],
      },
      {
        key: "brand",
        label: { ru: "Марка", ua: "Марка", en: "Brand" },
        type: "text",
      },
      {
        key: "model",
        label: { ru: "Модель", ua: "Модель", en: "Model" },
        type: "text",
      },
      {
        key: "memory",
        label: { ru: "Память", ua: "Пам'ять", en: "Memory" },
        type: "select",
        options: [
          { value: "64", label: { ru: "64 ГБ", ua: "64 ГБ", en: "64 GB" } },
          { value: "128", label: { ru: "128 ГБ", ua: "128 ГБ", en: "128 GB" } },
          { value: "256", label: { ru: "256 ГБ", ua: "256 ГБ", en: "256 GB" } },
          { value: "512", label: { ru: "512 ГБ", ua: "512 ГБ", en: "512 GB" } },
          { value: "1tb", label: { ru: "1 ТБ", ua: "1 ТБ", en: "1 TB" } },
        ],
      },
      {
        key: "ram",
        label: { ru: "RAM", ua: "RAM", en: "RAM" },
        type: "text",
      },
      {
        key: "condition",
        label: { ru: "Состояние", ua: "Стан", en: "Condition" },
        type: "select",
        options: [
          { value: "new", label: { ru: "Новое", ua: "Нове", en: "New" } },
          { value: "used", label: { ru: "Б/у", ua: "Б/в", en: "Used" } },
        ],
      },
      {
        key: "warranty",
        label: { ru: "Гарантия", ua: "Гарантія", en: "Warranty" },
        type: "boolean",
      },
      {
        key: "kit",
        label: { ru: "Комплектация", ua: "Комплектація", en: "Kit" },
        type: "text",
      },
    ],
  },
  {
    key: "business",
    icon: "📊",
    ua: "Бізнес та послуги",
    ru: "Бизнес и услуги",
    en: "Business & services",
    en: "Business & services",
    labelKey: "cat_business",
    color: "text-violet-600",
    bg: "bg-violet-50",
    filters: [
      {
        key: "service_type",
        label: { ru: "Тип услуги", ua: "Тип послуги", en: "Service type" },
        type: "select",
        options: [
          // 1. Ремонт и обслуживание
          { value: "phone_repair", label: { ru: "Ремонт телефонов", ua: "Ремонт телефонів", en: "Phone repair" } },
          { value: "laptop_repair", label: { ru: "Ремонт ноутбуков", ua: "Ремонт ноутбуків", en: "Laptop repair" } },
          { value: "appliance_repair", label: { ru: "Ремонт бытовой техники", ua: "Ремонт побутової техніки", en: "Appliance repair" } },
          { value: "fridge_repair", label: { ru: "Ремонт холодильников", ua: "Ремонт холодильників", en: "Refrigerator repair" } },
          { value: "washing_machine_repair", label: { ru: "Ремонт стиральных машин", ua: "Ремонт пральних машин", en: "Washing machine repair" } },
          { value: "pc_help", label: { ru: "Компьютерная помощь", ua: "Комп'ютерна допомога", en: "PC help" } },
          { value: "plumber", label: { ru: "Сантехник", ua: "Сантехнік", en: "Plumber" } },
          { value: "electrician", label: { ru: "Электрик", ua: "Електрик", en: "Electrician" } },
          { value: "handyman", label: { ru: "Мастер на час", ua: "Майстер на годину", en: "Handyman" } },
          { value: "furniture_assembly", label: { ru: "Сборка мебели", ua: "Збирання меблів", en: "Furniture assembly" } },
          { value: "furniture_repair", label: { ru: "Ремонт мебели", ua: "Ремонт меблів", en: "Furniture repair" } },
          { value: "auto_repair", label: { ru: "Ремонт авто", ua: "Ремонт авто", en: "Car repair" } },
          { value: "moto_repair", label: { ru: "Ремонт мото", ua: "Ремонт мото", en: "Moto repair" } },
          { value: "body_work", label: { ru: "Кузовные работы", ua: "Кузовні роботи", en: "Body work" } },
          { value: "ac_repair", label: { ru: "Ремонт кондиционеров", ua: "Ремонт кондиціонерів", en: "AC repair" } },
          { value: "ac_install", label: { ru: "Установка кондиционеров", ua: "Встановлення кондиціонерів", en: "AC installation" } },
          { value: "network_setup", label: { ru: "Настройка роутеров и интернета", ua: "Налаштування роутерів та інтернету", en: "Network setup" } },

          // 2. Строительство и ремонт
          { value: "apartment_renovation", label: { ru: "Ремонт квартир", ua: "Ремонт квартир", en: "Apartment renovation" } },
          { value: "painting", label: { ru: "Малярные работы", ua: "Малярні роботи", en: "Painting" } },
          { value: "plastering", label: { ru: "Штукатурка и шпаклёвка", ua: "Штукатурка та шпаклівка", en: "Plastering" } },
          { value: "tiling", label: { ru: "Плитка", ua: "Плитка", en: "Tiling" } },
          { value: "electrical_install", label: { ru: "Электромонтаж", ua: "Електромонтаж", en: "Electrical installation" } },
          { value: "plumbing_work", label: { ru: "Сантехнические работы", ua: "Сантехнічні роботи", en: "Plumbing work" } },
          { value: "floor_screed", label: { ru: "Стяжка полов", ua: "Стяжка підлоги", en: "Floor screed" } },
          { value: "roofing", label: { ru: "Кровельные работы", ua: "Покрівельні роботи", en: "Roofing" } },
          { value: "facade_work", label: { ru: "Фасадные работы", ua: "Фасадні роботи", en: "Facade work" } },

          // 3. Услуги для дома
          { value: "cleaning", label: { ru: "Уборка квартир", ua: "Прибирання квартир", en: "Apartment cleaning" } },
          { value: "general_cleaning", label: { ru: "Генеральная уборка", ua: "Генеральне прибирання", en: "Deep cleaning" } },
          { value: "window_cleaning", label: { ru: "Мытьё окон", ua: "Миття вікон", en: "Window cleaning" } },
          { value: "trash_removal", label: { ru: "Вывоз мусора", ua: "Вивіз сміття", en: "Trash removal" } },
          { value: "lawn_mowing", label: { ru: "Стрижка газонов", ua: "Стрижка газонів", en: "Lawn mowing" } },
          { value: "landscaping", label: { ru: "Ландшафтные работы", ua: "Ландшафтні роботи", en: "Landscaping" } },
          { value: "garden_care", label: { ru: "Уход за садом", ua: "Догляд за садом", en: "Garden care" } },
          { value: "moving", label: { ru: "Переезды", ua: "Переїзди", en: "Moving" } },
          { value: "movers", label: { ru: "Грузчики", ua: "Вантажники", en: "Movers" } },

          // 4. Фото, видео, дизайн
          { value: "photographer", label: { ru: "Фотограф", ua: "Фотограф", en: "Photographer" } },
          { value: "videographer", label: { ru: "Видеограф", ua: "Відеограф", en: "Videographer" } },
          { value: "video_editing", label: { ru: "Монтаж видео", ua: "Монтаж відео", en: "Video editing" } },
          { value: "design", label: { ru: "Дизайн (лого, баннеры)", ua: "Дизайн (лого, банери)", en: "Design" } },
          { value: "interior_design", label: { ru: "Дизайн интерьеров", ua: "Дизайн інтер'єрів", en: "Interior design" } },
          { value: "3d_motion", label: { ru: "3D / motion", ua: "3D / motion", en: "3D / motion" } },
          { value: "retouching", label: { ru: "Ретушь фотографий", ua: "Ретуш фотографій", en: "Photo retouching" } },
          { value: "smm", label: { ru: "SMM менеджмент", ua: "SMM менеджмент", en: "SMM management" } },

          // 5. Красота и здоровье
          { value: "manicure", label: { ru: "Маникюр", ua: "Манікюр", en: "Manicure" } },
          { value: "pedicure", label: { ru: "Педикюр", ua: "Педикюр", en: "Pedicure" } },
          { value: "hair_styling", label: { ru: "Укладка / окрашивание", ua: "Укладання / фарбування", en: "Hair styling" } },
          { value: "barber", label: { ru: "Барбер", ua: "Барбер", en: "Barber" } },
          { value: "cosmetologist", label: { ru: "Косметолог", ua: "Косметолог", en: "Cosmetologist" } },
          { value: "lashmaker", label: { ru: "Лашмейкер", ua: "Лашмейкер", en: "Lashmaker" } },
          { value: "massage", label: { ru: "Массажист", ua: "Масажист", en: "Massage therapist" } },
          { value: "tattoo", label: { ru: "Тату мастер", ua: "Тату майстер", en: "Tattoo artist" } },
          { value: "permanent_makeup", label: { ru: "Перманентный макияж", ua: "Перманентний макіяж", en: "Permanent makeup" } },

          // 6. Обучение
          { value: "tutor_english", label: { ru: "Репетитор английского", ua: "Репетитор англійської", en: "English tutor" } },
          { value: "tutor_german", label: { ru: "Репетитор немецкого", ua: "Репетитор німецької", en: "German tutor" } },
          { value: "exam_prep", label: { ru: "Подготовка к экзаменам", ua: "Підготовка до іспитів", en: "Exam prep" } },
          { value: "music_lessons", label: { ru: "Музыкальные уроки", ua: "Музичні уроки", en: "Music lessons" } },
          { value: "coding_courses", label: { ru: "Курсы программирования", ua: "Курси програмування", en: "Coding courses" } },
          { value: "drawing_teacher", label: { ru: "Учитель по рисованию", ua: "Вчитель малювання", en: "Drawing teacher" } },
          { value: "design_training", label: { ru: "Обучение 3D / дизайну", ua: "Навчання 3D / дизайну", en: "Design training" } },

          // 7. IT и digital
          { value: "web_dev", label: { ru: "Создание сайтов", ua: "Створення сайтів", en: "Web development" } },
          { value: "bot_dev", label: { ru: "Разработка Telegram-ботов", ua: "Розробка Telegram-ботів", en: "Bot development" } },
          { value: "miniapp_dev", label: { ru: "Разработка mini-apps", ua: "Розробка mini-apps", en: "Mini-app development" } },
          { value: "ads_setup", label: { ru: "Настройка рекламы", ua: "Налаштування реклами", en: "Ads setup" } },
          { value: "seo", label: { ru: "SEO", ua: "SEO", en: "SEO" } },
          { value: "tech_support", label: { ru: "Техподдержка", ua: "Техпідтримка", en: "Tech support" } },
          { value: "crm_setup", label: { ru: "Настройка CRM", ua: "Налаштування CRM", en: "CRM setup" } },

          // 8. Транспорт и автоуслуги
          { value: "taxi", label: { ru: "Такси", ua: "Таксі", en: "Taxi" } },
          { value: "passenger_transport", label: { ru: "Пассажирские перевозки", ua: "Пасажирські перевезення", en: "Passenger transport" } },
          { value: "delivery", label: { ru: "Доставка", ua: "Доставка", en: "Delivery" } },
          { value: "tow_truck", label: { ru: "Эвакуатор", ua: "Евакуатор", en: "Tow truck" } },
          { value: "cargo_transport", label: { ru: "Грузоперевозки", ua: "Вантажоперевезення", en: "Cargo transport" } },
          { value: "auto_service", label: { ru: "Услуги автосервиса", ua: "Послуги автосервісу", en: "Auto service" } },

          // 9. Животные
          { value: "grooming", label: { ru: "Груминг", ua: "Грумінг", en: "Grooming" } },
          { value: "pet_sitting", label: { ru: "Передержка", ua: "Перетримка", en: "Pet sitting" } },
          { value: "dog_training", label: { ru: "Дрессировка", ua: "Дресирування", en: "Dog training" } },
          { value: "vet_home", label: { ru: "Ветеринар на дом", ua: "Ветеринар додому", en: "Vet home visit" } },

          // 10. Ивенты и развлечения
          { value: "event_org", label: { ru: "Организация мероприятий", ua: "Організація заходів", en: "Event organization" } },
          { value: "host", label: { ru: "Ведущий", ua: "Ведучий", en: "Host" } },
          { value: "dj", label: { ru: "Диджей", ua: "Діджей", en: "DJ" } },
          { value: "photo_zone", label: { ru: "Фото-зоны", ua: "Фото-зони", en: "Photo zones" } },
          { value: "equipment_rental", label: { ru: "Прокат оборудования", ua: "Прокат обладнання", en: "Equipment rental" } },
          { value: "animators", label: { ru: "Детские аниматоры", ua: "Дитячі аніматори", en: "Animators" } },
          { value: "catering", label: { ru: "Кейтеринг / Еда", ua: "Кейтеринг / Їжа", en: "Catering / Food" } },

          // 11. Финансы и юридические
          { value: "legal_advice", label: { ru: "Юридические консультации", ua: "Юридичні консультації", en: "Legal advice" } },
          { value: "accountant", label: { ru: "Бухгалтер", ua: "Бухгалтер", en: "Accountant" } },
          { value: "business_reg", label: { ru: "Регистрация бизнеса", ua: "Реєстрація бізнесу", en: "Business registration" } },
          { value: "tax_advice", label: { ru: "Налоговые консультации", ua: "Податкові консультації", en: "Tax advice" } },
          { value: "translation", label: { ru: "Перевод документов", ua: "Переклад документів", en: "Translation" } },

          // 12. Для бизнеса
          { value: "b2b_rental", label: { ru: "Аренда оборудования", ua: "Оренда обладнання", en: "Equipment rental (B2B)" } },
          { value: "printing", label: { ru: "Полиграфия", ua: "Поліграфія", en: "Printing" } },
          { value: "business_cards", label: { ru: "Печать визиток / наклеек", ua: "Друк візиток / наклейок", en: "Business cards" } },
          { value: "courier", label: { ru: "Курьерские услуги", ua: "Кур'єрські послуги", en: "Courier services" } },
          { value: "hr", label: { ru: "HR / рекрутинг", ua: "HR / рекрутинг", en: "HR / Recruiting" } },
          { value: "marketing", label: { ru: "Маркетинг", ua: "Маркетинг", en: "Marketing" } },
        ],
      },
      {
        key: "onsite",
        label: { ru: "Выезд", ua: "Виїзд", en: "On-site" },
        type: "boolean",
      },
      {
        key: "price_type",
        label: { ru: "Тип цены", ua: "Тип ціни", en: "Price type" },
        type: "select",
        options: [
          { value: "fixed", label: { ru: "Фиксированная", ua: "Фіксована", en: "Fixed" } },
          { value: "negotiable", label: { ru: "По договоренности", ua: "За домовленістю", en: "Negotiable" } },
        ],
      },
      {
        key: "portfolio",
        label: { ru: "Портфолио", ua: "Портфоліо", en: "Portfolio" },
        type: "boolean",
      },
    ],
  },
  {
    key: "education",
    icon: "📚",
    ua: "Навчання",
    ru: "Учеба",
    en: "Education",
    labelKey: "cat_education",
    color: "text-yellow-600",
    bg: "bg-yellow-50",
    filters: [
      {
        key: "subtype",
        label: { ru: "Тип", ua: "Тип", en: "Type" },
        type: "select",
        options: [
          { value: "textbooks", label: { ru: "Учебники", ua: "Підручники", en: "Textbooks" } },
          { value: "stationery", label: { ru: "Канцелярия", ua: "Канцелярія", en: "Stationery" } },
          { value: "school_supplies", label: { ru: "Товары для школы", ua: "Товари для школи", en: "School supplies" } },
          { value: "literature", label: { ru: "Литература", ua: "Література", en: "Literature" } },
        ],
      },
      {
        key: "subject",
        label: { ru: "Предмет / Дисциплина", ua: "Предмет / Дисципліна", en: "Subject / Discipline" },
        type: "text",
      },
      {
        key: "condition",
        label: { ru: "Состояние", ua: "Стан", en: "Condition" },
        type: "select",
        options: [
          { value: "new", label: { ru: "Новое", ua: "Нове", en: "New" } },
          { value: "used", label: { ru: "Б/у", ua: "Б/в", en: "Used" } },
        ],
      },
    ],
  },
  {
    key: "fashion",
    icon: "👗",
    ua: "Мода і стиль",
    ru: "Мода и стиль",
    en: "Fashion & style",
    labelKey: "cat_fashion",
    filters: [
      {
        key: "subtype",
        label: { ru: "Тип", ua: "Тип", en: "Type" },
        type: "select",
        options: [
          { value: "clothing", label: { ru: "Одежда", ua: "Одяг", en: "Clothing" } },
          { value: "shoes", label: { ru: "Обувь", ua: "Взуття", en: "Shoes" } },
          { value: "accessories", label: { ru: "Аксессуары", ua: "Аксесуари", en: "Accessories" } },
        ],
      },
      {
        key: "size_clothes",
        label: { ru: "Размер одежды", ua: "Розмір одягу", en: "Clothing size" },
        type: "select",
        options: [
             { value: "xxs", label: { ru: "XXS", ua: "XXS", en: "XXS" } },
             { value: "xs", label: { ru: "XS", ua: "XS", en: "XS" } },
             { value: "s", label: { ru: "S", ua: "S", en: "S" } },
             { value: "m", label: { ru: "M", ua: "M", en: "M" } },
             { value: "l", label: { ru: "L", ua: "L", en: "L" } },
             { value: "xl", label: { ru: "XL", ua: "XL", en: "XL" } },
             { value: "xxl", label: { ru: "XXL", ua: "XXL", en: "XXL" } },
             { value: "3xl", label: { ru: "3XL", ua: "3XL", en: "3XL" } },
             { value: "4xl", label: { ru: "4XL", ua: "4XL", en: "4XL" } },
             { value: "oversize", label: { ru: "Оверсайз", ua: "Оверсайз", en: "Oversize" } },
        ]
      },
      {
        key: "size_shoes",
        label: { ru: "Размер обуви", ua: "Розмір взуття", en: "Shoe size" },
        type: "select",
        options: [
             { value: "35", label: { ru: "35", ua: "35", en: "35" } },
             { value: "36", label: { ru: "36", ua: "36", en: "36" } },
             { value: "37", label: { ru: "37", ua: "37", en: "37" } },
             { value: "38", label: { ru: "38", ua: "38", en: "38" } },
             { value: "39", label: { ru: "39", ua: "39", en: "39" } },
             { value: "40", label: { ru: "40", ua: "40", en: "40" } },
             { value: "41", label: { ru: "41", ua: "41", en: "41" } },
             { value: "42", label: { ru: "42", ua: "42", en: "42" } },
             { value: "43", label: { ru: "43", ua: "43", en: "43" } },
             { value: "44", label: { ru: "44", ua: "44", en: "44" } },
             { value: "45", label: { ru: "45", ua: "45", en: "45" } },
             { value: "46", label: { ru: "46", ua: "46", en: "46" } },
             { value: "47", label: { ru: "47", ua: "47", en: "47" } },
        ]
      },
      {
        key: "gender",
        label: { ru: "Пол", ua: "Стать", en: "Gender" },
        type: "select",
        options: [
          { value: "male", label: { ru: "Мужской", ua: "Чоловічий", en: "Male" } },
          { value: "female", label: { ru: "Женский", ua: "Жіночий", en: "Female" } },
          { value: "unisex", label: { ru: "Унисекс", ua: "Унісекс", en: "Unisex" } },
        ],
      },
      {
        key: "season",
        label: { ru: "Сезон", ua: "Сезон", en: "Season" },
        type: "select",
        options: [
          { value: "summer", label: { ru: "Лето", ua: "Літо", en: "Summer" } },
          { value: "winter", label: { ru: "Зима", ua: "Зима", en: "Winter" } },
          { value: "demi", label: { ru: "Демисезон", ua: "Демісезон", en: "Demi-season" } },
          { value: "all", label: { ru: "Всесезон", ua: "Всесезон", en: "All season" } },
        ],
      },
      {
        key: "brand",
        label: { ru: "Бренд", ua: "Бренд", en: "Brand" },
        type: "text",
      },
      {
        key: "material",
        label: { ru: "Материал", ua: "Матеріал", en: "Material" },
        type: "text",
      },
      {
        key: "color",
        label: { ru: "Цвет", ua: "Колір", en: "Color" },
        type: "text",
      },
      {
        key: "condition",
        label: { ru: "Состояние", ua: "Стан", en: "Condition" },
        type: "select",
        options: [
          { value: "new", label: { ru: "Новое", ua: "Нове", en: "New" } },
          { value: "used", label: { ru: "Б/у", ua: "Б/в", en: "Used" } },
        ],
      },
    ],
  },
  {
    key: "hobby_sport",
    icon: "🎯",
    ua: "Хобі, відпочинок і спорт",
    ru: "Хобби, отдых и спорт",
    en: "Hobby, leisure & sport",
    labelKey: "cat_hobby_sport",
    filters: [
      {
        key: "subtype",
        label: { ru: "Тип", ua: "Тип", en: "Type" },
        type: "select",
        options: [
          { value: "antiques", label: { ru: "Антиквариат / коллекции", ua: "Антикваріат / колекції", en: "Antiques / collections" } },
          { value: "music_instruments", label: { ru: "Музыкальные инструменты", ua: "Музичні інструменти", en: "Musical instruments" } },
          { value: "sport_leisure", label: { ru: "Спорт / отдых", ua: "Спорт / відпочинок", en: "Sport / leisure" } },
          { value: "bicycles", label: { ru: "Вело", ua: "Вело", en: "Bicycles" } },
          { value: "militaria", label: { ru: "Милитария", ua: "Мілітарія", en: "Militaria" } },
          { value: "drones", label: { ru: "Квадрокоптеры и аксессуары", ua: "Квадрокоптери та аксесуари", en: "Drones and accessories" } },
          { value: "books", label: { ru: "Книги / журналы", ua: "Книги / журнали", en: "Books / magazines" } },
          { value: "media", label: { ru: "CD / DVD / пластинки / кассеты", ua: "CD / DVD / платівки / касети", en: "CD / DVD / vinyl / cassettes" } },
          { value: "tickets", label: { ru: "Билеты", ua: "Квитки", en: "Tickets" } },
          { value: "travel_companions", label: { ru: "Поиск попутчиков", ua: "Пошук попутників", en: "Travel companions" } },
          { value: "musicians", label: { ru: "Поиск групп / музыкантов", ua: "Пошук груп / музикантів", en: "Musicians / bands" } },
          { value: "other", label: { ru: "Другое", ua: "Інше", en: "Other" } },
        ],
      },
      {
        key: "condition",
        label: { ru: "Состояние", ua: "Стан", en: "Condition" },
        type: "select",
        options: [
          { value: "new", label: { ru: "Новое", ua: "Нове", en: "New" } },
          { value: "used", label: { ru: "Б/у", ua: "Б/в", en: "Used" } },
        ],
      },
      {
        key: "manufacturer",
        label: { ru: "Производитель", ua: "Виробник", en: "Manufacturer" },
        type: "text",
      },
    ],
  },
  {
    key: "free",
    icon: "🎁",
    ua: "Віддам безкоштовно",
    ru: "Отдам бесплатно",
    en: "Give away free",
    labelKey: "cat_free",
    filters: [
      {
        key: "condition",
        label: { ru: "Состояние", ua: "Стан", en: "Condition" },
        type: "select",
        options: [
          { value: "new", label: { ru: "Новое", ua: "Нове", en: "New" } },
          { value: "used", label: { ru: "Б/у", ua: "Б/в", en: "Used" } },
        ],
      },
    ],
  },
  {
    key: "exchange",
    icon: "🔁",
    ua: "Обмін",
    ru: "Обмен",
    en: "Exchange",
    labelKey: "cat_exchange",
    labelKey: "cat_exchange",
    filters: [
      {
        key: "offer",
        label: { ru: "Что отдаёшь", ua: "Що віддаєш", en: "What you offer" },
        type: "text",
      },
      {
        key: "request",
        label: { ru: "На что меняешь", ua: "На що міняєш", en: "What you want" },
        type: "text",
      },
      {
        key: "surcharge",
        label: { ru: "Доплата", ua: "Доплата", en: "Surcharge" },
        type: "range",
      },
    ],
  },
  {
    key: "help_offer",
    icon: "🤝",
    ua: "Допомога",
    ru: "Помощь",
    en: "Help",
    labelKey: "cat_help_offer",
    color: "text-rose-600",
    bg: "bg-rose-50",
    filters: [
      {
        key: "subtype",
        label: { ru: "Тип помощи", ua: "Тип допомоги", en: "Help type" },
        type: "select",
        options: [
          { value: "physical", label: { ru: "Физическая помощь", ua: "Фізична допомога", en: "Physical help" } },
          { value: "advice", label: { ru: "Совет / Консультация", ua: "Порада / Консультація", en: "Advice" } },
          { value: "transport", label: { ru: "Транспорт / Подвезти", ua: "Транспорт / Підвезти", en: "Transport" } },
          { value: "professional", label: { ru: "Проф. услуги", ua: "Проф. послуги", en: "Pro services" } },
          { value: "other", label: { ru: "Другое", ua: "Інше", en: "Other" } },
        ],
      },
    ],
  },

];
